# Generated by Django 4.0.2 on 2022-02-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0002_alter_meal_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='slug',
            field=models.SlugField(default='a', unique=True),
        ),
        migrations.AlterField(
            model_name='variety',
            name='image',
            field=models.ImageField(blank=True, default='variety.jpg', null=True, upload_to='variety'),
        ),
    ]
