# Generated by Django 4.0.2 on 2022-02-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0007_meal_updated_variety_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='discount',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='meal',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
