# Generated by Django 4.0.2 on 2022-02-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0009_alter_meal_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='menu',
        ),
    ]
