# Generated by Django 4.0.2 on 2022-02-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0010_remove_meal_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
