# Generated by Django 4.0.2 on 2022-02-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0014_contact_status_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
