# Generated by Django 4.0.2 on 2022-02-22 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0018_paidorder_alter_profile_image_shopcart_shipping_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paidorder',
            options={'managed': True, 'verbose_name': 'PaidOrder', 'verbose_name_plural': 'PaidOrders'},
        ),
        migrations.AlterModelOptions(
            name='shipping',
            options={'managed': True, 'verbose_name': 'Shipping', 'verbose_name_plural': 'Shippings'},
        ),
        migrations.AlterModelOptions(
            name='shopcart',
            options={'managed': True, 'verbose_name': 'Shopcart', 'verbose_name_plural': 'Shopcarts'},
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='PaidOrder',
        ),
        migrations.AddField(
            model_name='shipping',
            name='admin_remark',
            field=models.CharField(default='new', max_length=100),
        ),
        migrations.AddField(
            model_name='shipping',
            name='paidorder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodie.paidorder'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('ppending', 'ppending'), ('processing', 'processing'), ('shipping', 'shipping'), ('delivered', 'delivered')], default='new', max_length=50),
        ),
        migrations.AlterModelTable(
            name='paidorder',
            table='paidOrder',
        ),
        migrations.AlterModelTable(
            name='shipping',
            table='shipping',
        ),
        migrations.AlterModelTable(
            name='shopcart',
            table='shopcart',
        ),
    ]
