# Generated by Django 4.0.2 on 2022-02-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0020_alter_shipping_admin_remark_alter_shipping_paidorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='max_order',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='meal',
            name='min_order',
            field=models.IntegerField(default=1),
        ),
    ]
