# Generated by Django 4.0.2 on 2022-02-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0022_remove_shipping_paidorder_remove_shopcart_meal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='spicy',
            field=models.CharField(max_length=100),
        ),
    ]
