# Generated by Django 4.0.2 on 2022-03-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0024_profile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='cart_code',
            field=models.AutoField(default=101, primary_key=True, serialize=False),
        ),
    ]
