# Generated by Django 4.0.2 on 2022-03-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0025_remove_profile_id_profile_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cart_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
