# Generated by Django 4.0.2 on 2022-02-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0003_alter_shopcart_how_spicey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='spicy',
        ),
    ]
