# Generated by Django 4.0.2 on 2022-03-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0004_remove_shopcart_spicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='admin_remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('ppending', 'ppending'), ('processing', 'processing'), ('shipping', 'shipping'), ('delivered', 'delivered')], default='new', max_length=50, null=True),
        ),
    ]
